// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8xj3IoiUNYdB0KGmy87PIWGWTENgdCYo',
    appId: '1:349953827130:web:2e6f9bc1fca806a9be3003',
    messagingSenderId: '349953827130',
    projectId: 'todois-2aaaa',
    authDomain: 'todois-2aaaa.firebaseapp.com',
    databaseURL: 'https://todois-2aaaa-default-rtdb.firebaseio.com',
    storageBucket: 'todois-2aaaa.appspot.com',
    measurementId: 'G-FTKVGY32ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFWPzEhxooaxXdpk9UiSc4BdOQQTyqeaE',
    appId: '1:349953827130:android:b3f6282c1deda12bbe3003',
    messagingSenderId: '349953827130',
    projectId: 'todois-2aaaa',
    databaseURL: 'https://todois-2aaaa-default-rtdb.firebaseio.com',
    storageBucket: 'todois-2aaaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYRvT7pJnGdCYKDKyvGUl_oHFEVDjqVGE',
    appId: '1:349953827130:ios:1072fc9b3187dd94be3003',
    messagingSenderId: '349953827130',
    projectId: 'todois-2aaaa',
    databaseURL: 'https://todois-2aaaa-default-rtdb.firebaseio.com',
    storageBucket: 'todois-2aaaa.appspot.com',
    iosClientId: '349953827130-hcvjibv6apnrsr4ok1m8b982g1n65tck.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYRvT7pJnGdCYKDKyvGUl_oHFEVDjqVGE',
    appId: '1:349953827130:ios:606564310fac2188be3003',
    messagingSenderId: '349953827130',
    projectId: 'todois-2aaaa',
    databaseURL: 'https://todois-2aaaa-default-rtdb.firebaseio.com',
    storageBucket: 'todois-2aaaa.appspot.com',
    iosClientId: '349953827130-uik7dps14qmqulqrm2krsppo2o7prfan.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
